import 'package:flutter/material.dart';

class Constants {
  static const Color darkPrimary = Color.fromARGB(255, 2, 32, 7);
  static const Color primaryDark = Color.fromARGB(255, 6, 66, 10);
  static const Color secondary = Color.fromARGB(255, 36, 55, 37);
  static const Color bottomBar = Color.fromARGB(255, 13, 43, 16);
  static const Color textColor = Color.fromARGB(255, 212, 212, 212);

  static const List<String> videoFormats = [
    '.webm',
    '.mkv',
    '.flv',
    '.vob',
    '.ogv',
    '.ogg',
    '.drc',
    '.gif',
    '.gifv',
    '.mng',
    '.avi',
    '.MTS',
    '.M2TS',
    '.TS',
    '.mov',
    '.qt',
    '.wmv',
    '.yuv',
    '.rm',
    '.rmvb',
    '.viv',
    '.asf',
    '.amv',
    '.mp4',
    '.m4p',
    '.m4v',
    '.mpg',
    '.mp2',
    '.mpeg',
    '.mpe',
    '.mpv',
    '.m2v',
    '.svi',
    '.3gp',
    '.3g2',
    '.mxf',
    '.roq',
    '.nsv',
    '.fv4',
    '.f4p',
    '.f4a',
    '.f4b',
  ];

  static const Map<String, dynamic> formatNames = {
    '.webm': 'WebM',
    '.mkv': 'Matroska',
    '.flv': 'Flash Video',
    '.vob': 'Vob',
    '.ogv': 'Ogg Video',
    '.ogg': 'Ogg Video',
    '.drc': 'Dirac',
    '.gif': 'GIF',
    '.gifv': 'HTML',
    '.mng': 'Multiple-image Network Graphics',
    '.avi': 'AVI',
    '.MTS': 'MPEG Transport Stream',
    '.M2TS': 'MPEG Transport Stream',
    '.TS': 'MPEG Transport Stream',
    '.mov': 'QuickTime File Format',
    '.qt': 'QuickTime File Format',
    '.wmv': 'Windows Media Video',
    '.yuv': 'Raw Video Format',
    '.rm': 'Real Media',
    '.rmvb': 'Real Media Variable Bitrate',
    '.viv': 'ViroActive',
    '.asf': 'Advanced Sysytems Format',
    '.amv': 'AMV Video Format',
    '.mp4': 'MPEG-4 Part 14',
    '.m4p': 'MPEG-4 Part 14',
    '.m4v': 'MPEG-4 Part 14',
    '.mpg': 'MPEG-1',
    '.mp2': 'MPEG-1',
    '.mpeg': 'MPEG-1',
    '.mpe': 'MPEG-1',
    '.mpv': 'MPEG-1',
    '.m2v': 'MPEG-2',
    '.svi': 'SVI',
    '.3gp': '3GPP',
    '.3g2': '3GPP2',
    '.mxf': 'Material Exchange Format',
    '.roq': 'ROQ',
    '.nsv': 'Nullsoft Streaming Video',
    '.fv4': 'Flash Video',
    '.f4p': 'Flash Video',
    '.f4a': 'Flash Video',
    '.f4b': 'Flash Video',
  };

  static const Map<String, List<String>> langAbbr = {
    'Afar': ['aa', 'aar'],
    'Abkhazian': ['ab', 'abk'],
    'Avestan': ['ae', 'ave'],
    'Afrikaans': ['af', 'afr'],
    'Akan': ['ak', 'aka'],
    'Amharic': ['am', 'amh'],
    'Aragonese': ['an', 'arg'],
    'Arabic': ['ar', 'ara'],
    'Assamese': ['as', 'asm'],
    'Avaric': ['av', 'ava'],
    'Aymara': ['ay', 'aym'],
    'Azerbaijani': ['az', 'aze'],
    'Bashkir': ['ba', 'bak'],
    'Belarusian': ['be', 'bel'],
    'Bulgarian': ['bg', 'bul'],
    'Bihari': ['bh', 'bih'],
    'Bislama': ['bi', 'bis'],
    'Bambara': ['bm', 'bam'],
    'Bengali': ['bn', 'ben'],
    'Tibetan': ['bo', 'tib'],
    'Breton': ['br', 'bre'],
    'Bosnian': ['bs', 'bos'],
    'Catalan': ['ca', 'cat'],
    'Chechen': ['ce', 'che'],
    'Chamorro': ['ch', 'cha'],
    'Corsican': ['co', 'cos'],
    'Cree': ['cr', 'cre'],
    'Czech': ['cs', 'cze'],
    'Church slavic': ['cu', 'chu'],
    'Chuvash': ['cv', 'chv'],
    'Welsh': ['cy', 'wel'],
    'Danish': ['da', 'dan'],
    'German': ['de', 'ger'],
    'Maldivian': ['dv', 'div'],
    'Dzongkha': ['dz', 'dzo'],
    'Ewe': ['ee', 'ewe'],
    'Greek': ['el', 'gre'],
    'English': ['en', 'eng'],
    'Esperanto': ['eo', 'epo'],
    'Spanish': ['es', 'spa'],
    'Estonian': ['et', 'est'],
    'Basque': ['eu', 'baq'],
    'Persian': ['fa', 'per'],
    'Fulah': ['ff', 'ful'],
    'Finnish': ['fi', 'fin'],
    'Fijian': ['fj', 'fij'],
    'Faroese': ['fo', 'fao'],
    'French': ['fr', 'fre'],
    'Western Frisian': ['fy', 'fry'],
    'Irish': ['ga', 'gle'],
    'Gaelic': ['gd', 'gla'],
    'Galician': ['gl', 'glg'],
    'Guarani': ['gn', 'grn'],
    'Gujarati': ['gu', 'guj'],
    'Manx': ['gv', 'glv'],
    'Hausa': ['ha', 'hau'],
    'Hebrew': ['he', 'heb'],
    'Hindi': ['hi', 'hin'],
    'Hiri Motu': ['ho', 'hmo'],
    'Croatian': ['hr', 'hrv'],
    'Haitian': ['ht', 'hat'],
    'Hungarian': ['hu', 'hun'],
    'Armenian': ['hy', 'arm'],
    'Herero': ['hz', 'her'],
    'Interlingua': ['ia', 'ina'],
    'Indonesian': ['id', 'ind'],
    'Interlingue': ['ie', 'ile'],
    'Igbo': ['ig', 'ibo'],
    'Sichuan Yi': ['ii', 'iii'],
    'Inupiaq': ['ik', 'ipk'],
    'Ido': ['io', 'ido'],
    'Icelandic': ['is', 'ice'],
    'Italian': ['it', 'ita'],
    'Inuktitut': ['iu', 'iku'],
    'Japanese': ['ja', 'jpn'],
    'Javanese': ['jv', 'jav'],
    'Georgian': ['ka', 'geo'],
    'Kongo': ['kg', 'kon'],
    'Kikuyu': ['ki', 'kik'],
    'Kuanyama': ['kj', 'kua'],
    'Kazakh': ['kk', 'kaz'],
    'Greenlandic': ['kl', 'kal'],
    'Central Khmer': ['km', 'khm'],
    'Kannada': ['kn', 'kan'],
    'Korean': ['ko', 'kor'],
    'Kanuri': ['kr', 'kau'],
    'Kashmiri': ['ks', 'kas'],
    'Kurdish': ['ku', 'kur'],
    'Komi': ['kv', 'kom'],
    'Cornish': ['kw', 'cor'],
    'Kirghiz': ['ky', 'kir'],
    'Latin': ['la', 'lat'],
    'Luxembourgish': ['lb', 'ltz'],
    'Ganda': ['lg', 'lug'],
    'Limburgan': ['li', 'lim'],
    'Lingala': ['ln', 'lin'],
    'Lao': ['lo', 'lao'],
    'Lithuanian': ['lt', 'lit'],
    'Luba-Katanga': ['lu', 'lub'],
    'Latvian': ['lv', 'lav'],
    'Malagasy': ['mg', 'mlg'],
    'Marshallese': ['mh', 'mah'],
    'Maori': ['mi', 'mao'],
    'Macedonian': ['mk', 'mac'],
    'Malayalam': ['ml', 'mal'],
    'Mongolian': ['ml', 'mon'],
    'Marathi': ['mr', 'mar'],
    'Malay': ['ms', 'may'],
    'Maltese': ['mt', 'mlt'],
    'Burmese': ['my', 'bur'],
    'Nauru': ['na', 'nau'],
    'Norwegian Bokmal': ['nb', 'nob'],
    'North Ndebele': ['nd', 'nde'],
    'Nepali': ['ne', 'nep'],
    'Ndonga': ['ng', 'ndo'],
    'Dutch': ['nl', 'dut'],
    'Norwegian Nynorsk': ['nn', 'nno'],
    'Norwegian': ['no', 'nor'],
    'South Ndebele': ['nr', 'nbl'],
    'Navaho': ['nv', 'nav'],
    'Nyanja': ['ny', 'nya'],
    'Occitan': ['oc', 'oci'],
    'Ojibwa': ['oj', 'oji'],
    'Oromo': ['om', 'orm'],
    'Oriya': ['or', 'ori'],
    'Ossetian': ['os', 'oss'],
    'Punjabi': ['pa', 'pan'],
    'Pali': ['pi', 'pli'],
    'Polish': ['pl', 'pol'],
    'Pashto': ['ps', 'pus'],
    'Portuguese': ['pt', 'por'],
    'Quechua': ['qu', 'que'],
    'Romansh': ['rm', 'rom'],
    'Rundi': ['rn', 'run'],
    'Romanian': ['ro', 'rum'],
    'Russian': ['ru', 'rus'],
    'Kinyarwanda': ['rw', 'kin'],
    'Sanskrit': ['sa', 'san'],
    'Sardinian': ['sc', 'srd'],
    'Sindhi': ['sd', 'snd'],
    'Northern Sami': ['se', 'sme'],
    'Sango': ['sg', 'sag'],
    'Sinhalese': ['si', 'sin'],
    'Slovak': ['sk', 'slo'],
    'Slovenian': ['sl', 'slv'],
    'Samoan': ['sm', 'smo'],
    'Shona': ['sn', 'sna'],
    'Somali': ['so', 'som'],
    'Albanian': ['sq', 'alb'],
    'Serbian': ['sr', 'srp'],
    'Swati': ['ss', 'ssw'],
    'Sotho, Southern': ['st', 'sot'],
    'Sundanese': ['su', 'sun'],
    'Swedish': ['sv', 'swe'],
    'Swahili': ['sw', 'swa'],
    'Tamil': ['ta', 'tam'],
    'Telugu': ['te', 'tel'],
    'Tajik': ['tg', 'tgk'],
    'Thai': ['th', 'tha'],
    'Tigrinya': ['ti', 'tir'],
    'Turkmen': ['tk', 'tuk'],
    'Tagalog': ['tl', 'tgl'],
    'Tswana': ['tn', 'tsn'],
    'Tonga': ['to', 'ton'],
    'Turkish': ['tr', 'tur'],
    'Tsonga': ['ts', 'tso'],
    'Tatar': ['tt', 'tat'],
    'Twi': ['tw', 'twi'],
    'Tahitian': ['ty', 'tah'],
    'Uighur': ['ug', 'uig'],
    'Ukrainian': ['uk', 'ukr'],
    'Urdu': ['ur', 'urd'],
    'Uzbek': ['uz', 'uzb'],
    'Venda': ['ve', 'ven'],
    'Vietnamese': ['vi', 'vie'],
    'Volapuk': ['vo', 'vol'],
    'Walloon': ['wa', 'wln'],
    'Wolof': ['wo', 'wol'],
    'Xhosa': ['xh', 'xho'],
    'Yiddish': ['yi', 'yid'],
    'Yoruba': ['yo', 'yor'],
    'Zhuang': ['za', 'zha'],
    'Chinese': ['zh', 'chi'],
    'Zulu': ['zu', 'zul'],
  };
}
